apiVersion: v1
kind: Service
metadata:
  name: flipkart-backend
  namespace: flipkart
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: flipkart-backend
    role: stable
spec:
  selector:
    app: flipkart-backend
  ports:
    - name: http
      port: 4000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: flipkart-backend-canary
  namespace: flipkart
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: flipkart-backend
    role: canary
spec:
  selector:
    app: flipkart-backend
  ports:
    - name: http
      port: 4000
      targetPort: http
