apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-app
  namespace: payments
  labels:
    app: payments-api
    owner: payments-team
    tenant: payments
imagePullSecrets:
  - name: ghcr-pull-secret
