apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-demo
  namespace: flipkart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure-demo
  template:
    metadata:
      labels:
        app: insecure-demo
    spec:
      containers:
        - name: app
          image: nginx:latest
          securityContext:
            privileged: true
