# ArgoCD App: Deploy RBAC examples from W10 morning lab
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/X-BRAIN-CDO-09/LeHoangTrungKien-aws-accelerator-p2.git
    path: cloud/w10/temp/security-rbac-admission/rbac
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true

