apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-consumer
  namespace: team-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-consumer
  template:
    metadata:
      labels:
        app: secret-consumer
    spec:
      containers:
        - name: app
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args:
            - "while true; do date; cat /etc/app-secrets/DB_PASSWORD; sleep 10; done"
          volumeMounts:
            - name: app-secrets
              mountPath: /etc/app-secrets
              readOnly: true
      volumes:
        - name: app-secrets
          secret:
            secretName: app-secrets
