apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alice-demo-deployer
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: alice
    namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-deployer

