apiVersion: v1
kind: ServiceAccount
metadata:
  name: alice
  namespace: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
  namespace: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
  namespace: demo

