apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: team-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre
  namespace: team-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer
  namespace: team-a
