apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: flipkart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre
  namespace: flipkart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer
  namespace: flipkart
