apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-cluster-store
  labels:
    owner: platform-team
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            namespace: demo
            key: access-key
          secretAccessKeySecretRef:
            name: aws-creds
            namespace: demo
            key: secret-key
